# Generated by Django 3.2.7 on 2021-10-05 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zwb_book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeopleInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('people_name', models.CharField(max_length=10, unique=True)),
                ('gender', models.SmallIntegerField(choices=[(2, 'female'), (1, 'male')], default=1)),
                ('description', models.CharField(max_length=100, null=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zwb_book.bookinfo')),
            ],
            options={
                'db_table': 'peopleinfo',
            },
        ),
    ]
