# Generated by Django 3.2.7 on 2021-10-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zwb_book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peopleinfo',
            name='gender',
            field=models.SmallIntegerField(choices=[(2, 'female'), (1, 'male')], default=1),
        ),
    ]
